<?php

namespace FunQ\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserBundleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserBundleRepository extends EntityRepository
{
}
