fun_q:
    resource: "@FunQBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation