FunQ\UserBundle\Entity\UserBundle:
    type: entity
    table: null
    repositoryClass: FunQ\UserBundle\Entity\UserBundleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        roles:
            type: json_array
        isActive:
            type: boolean
        email:
            type: string
            length: 255
    lifecycleCallbacks: {  }
