fun_q_user:
    resource: "@FunQBundle/Resources/config/routing/user.yml"
    prefix:   /user




<<<<<<< HEAD

=======
>>>>>>> ac50c402d025744d58e6bf65c3578fb94b8661b2
#kill prefix to / for future..
fun_q_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: FunQBundle:Default:index }
