fun_q_user:
    resource: "@FunQBundle/Resources/config/routing/user.yml"
    prefix:   /user

fun_q_homepage:
    path:     /hello/{name}/{count}
    defaults: { _controller: FunQBundle:Default:index }
